name: weather_app
description: A new Flutter application.

version: 5.2.0+14

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  url_launcher: ^6.0.20
  flutter_typeahead: ^3.2.4
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  geolocator: ^8.2.0
  cupertino_icons: ^1.0.4
  shimmer: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^9.3.2
  provider: ^6.0.2
  parse_server_sdk_flutter: ^3.1.0
  iconsax: ^0.0.8
  animate_do: ^2.1.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
